// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repositories/rating_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/stwrtrio/movie-festival-api/internal/models"
)

// MockRatingRepository is a mock of RatingRepository interface.
type MockRatingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRatingRepositoryMockRecorder
}

// MockRatingRepositoryMockRecorder is the mock recorder for MockRatingRepository.
type MockRatingRepositoryMockRecorder struct {
	mock *MockRatingRepository
}

// NewMockRatingRepository creates a new mock instance.
func NewMockRatingRepository(ctrl *gomock.Controller) *MockRatingRepository {
	mock := &MockRatingRepository{ctrl: ctrl}
	mock.recorder = &MockRatingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRatingRepository) EXPECT() *MockRatingRepositoryMockRecorder {
	return m.recorder
}

// RateMovie mocks base method.
func (m *MockRatingRepository) RateMovie(ctx context.Context, rating *models.Rating) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RateMovie", ctx, rating)
	ret0, _ := ret[0].(error)
	return ret0
}

// RateMovie indicates an expected call of RateMovie.
func (mr *MockRatingRepositoryMockRecorder) RateMovie(ctx, rating interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RateMovie", reflect.TypeOf((*MockRatingRepository)(nil).RateMovie), ctx, rating)
}

// UpdateMovieRating mocks base method.
func (m *MockRatingRepository) UpdateMovieRating(ctx context.Context, movieID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMovieRating", ctx, movieID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMovieRating indicates an expected call of UpdateMovieRating.
func (mr *MockRatingRepositoryMockRecorder) UpdateMovieRating(ctx, movieID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMovieRating", reflect.TypeOf((*MockRatingRepository)(nil).UpdateMovieRating), ctx, movieID)
}
